services:
  expenseowl:
    image: tanq16/expenseowl:main
    restart: unless-stopped
    ports:
      - ${EXPENSEOWL_PORT}:8080 
    volumes:
      - ./data:/app/data 
    networks:
      - caddy

networks:
  caddy:
    external: true 