name: expenseowl
services:
  expenseowl:
    image: tanq16/expenseowl:main
    restart: unless-stopped
    # ports:
    #   - ${EXPENSEOWL_PORT}:8080 
    volumes:
      - /home/virajs-server/docker/expenseowl/data:/app/data 
    networks:
      - nginx

networks:
  nginx:
    external: true 