services:
  kdenlive:
    image: lscr.io/linuxserver/kdenlive:latest
    container_name: kdenlive
    environment:
      - PUID=${PUID}
      - PGID=${PGID}
      - TZ=${TZ}
    volumes:
      - ./data/config:/config
    ports:
      - ${KDENLIVE_PORT_1}:3000
      - ${KDENLIVE_PORT_2}:3001
    shm_size: "1gb" #optional
    restart: unless-stopped
    networks:
      - caddy
networks:
  caddy:
    external: true    