name: navidrome
services:
  navidrome:
    image: deluan/navidrome:latest
    user: ${PUID}:${PGID}
    # ports:
    #   - "${NAVIDROME_PORT}:4533"
    restart: unless-stopped
    volumes:
      - "/home/virajs-server/docker/navidrome/data/data:/data"
      - "/home/virajs-server/docker/navidrome/data/music:/music:ro"
    networks:
      - nginx
networks:
  nginx:
    external: true