name: n8n
services:
  n8n:
    image: n8nio/n8n:latest
    container_name: n8n
    ports:
      - "5678:5678"
    environment:
      GENERIC_TIMEZONE: "Asia/Kolkata"
      TZ: "Asia/Kolkata"

      DB_SQLITE_POOL_SIZE: 2
      N8N_BLOCK_ENV_ACCESS_IN_NODE: "false"
      N8N_GIT_NODE_DISABLE_BARE_REPOS: "true"
      DOMAIN_NAME: ${DOMAIN_NAME}
      SUBDOMAIN: ${SUBDOMAIN}
      VUE_APP_URL_BASE_API: ${VUE_APP_URL_BASE_API}
      DYLMS_EMAIL: ${DYLMS_EMAIL}
      DYLMS_PASSWORD: ${DYLMS_PASSWORD}
      HONEYGAIN_TOKEN: ${HONEYGAIN_TOKEN}
      NTFY_HONEYGAIN_CHANNEL: ${NTFY_HONEYGAIN_CHANNEL}
      N8N_ENFORCE_SETTINGS_FILE_PERMISSIONS: "true"
      N8N_RUNNERS_ENABLED: "true"

    volumes:
      - /home/virajs-server/docker/n8n/data:/home/node/.n8n

    networks:
      - nginx

networks:
  nginx:
    external: true
