name: vikunja
services:
  vikunja:
    image: vikunja/vikunja
    container_name: vikunja
    environment:
      VIKUNJA_SERVICE_PUBLICURL: https://vikunja.viraj.top/
      VIKUNJA_DATABASE_HOST: vikunja-db
      VIKUNJA_DATABASE_PASSWORD: "Shirodkar@45"
      VIKUNJA_DATABASE_TYPE: mysql
      VIKUNJA_DATABASE_USER: vikunja
      VIKUNJA_DATABASE_DATABASE: vikunja
      VIKUNJA_SERVICE_JWTSECRET: "3spU8so3jfoKktY+Lw=="
    # ports:
    #   - 3456:3456
    volumes:
      - /home/virajs-server/docker/vikunja/files:/app/vikunja/files
    depends_on:
      db:
        condition: service_healthy
    restart: unless-stopped
    networks:
      - nginx

  db:
    image: mariadb:10
    command: --character-set-server=utf8mb4 --collation-server=utf8mb4_unicode_ci
    environment:
      MYSQL_ROOT_PASSWORD: Shirodkar@45
      MYSQL_USER: vikunja
      MYSQL_PASSWORD: Shirodkar@45
      MYSQL_DATABASE: vikunja
    volumes:
      - /home/virajs-server/docker/vikunja/db:/var/lib/mysql
    restart: unless-stopped
    healthcheck:
      test:
        [
          "CMD-SHELL",
          "mysqladmin ping -h localhost -u $$MYSQL_USER --password=$$MYSQL_PASSWORD",
        ]
      interval: 2s
      start_period: 30s
    networks:
      - nginx
networks:
  nginx:
    external: true            
