name: intellij
services:
  intellij:
    image: lscr.io/linuxserver/intellij-idea:latest
    container_name: intellij
    environment:
      - PUID=${PUID}
      - PGID=${PGID}
      - TZ=${TZ}
    volumes:
      - /home/virajs-server/docker/intellij-idea/data/config:/config
    shm_size: "1gb"
    restart: "no"
    networks:
      - nginx
networks:
  nginx:
    external: true