services:
  gimp:
    image: lscr.io/linuxserver/gimp:latest
    container_name: gimp
    environment:
      - PUID=${PUID}
      - PGID=${PGID}
      - TZ=${TZ}
    volumes:
      - ./data/config:/config
    ports:
      - ${GIMP_PORT_1}:3000
      - ${GIMP_PORT_2}:3001
    shm_size: "1gb"
    restart: unless-stopped
    networks:
      - caddy
networks:
  caddy:
    external: true    