services:
  filebrowser:
    image: filebrowser/filebrowser:latest
    container_name: filebrowser
    restart: unless-stopped
    # ports:
    #   - "${FILEBROWSER_PORT}:80"
    environment:
      - PUID=${PUID}
      - PGID=${PGID}   
    volumes:
      - /home/virajs:/srv
      - ./data/filebrowser_database:/database
      - ./data/filebrowser_config:/config
    networks:
      - caddy

networks:
  caddy:
    external: true 