name: filebrowser
services:
  filebrowser:
    image: filebrowser/filebrowser:latest
    container_name: filebrowser
    restart: unless-stopped
    # ports:
    #   - "${FILEBROWSER_PORT}:80"
    environment:
      - PUID=${PUID}
      - PGID=${PGID}   
    volumes:
      - /home/virajs-server:/srv
      - /mnt/1TB_HDD:/srv/1TB_HDD
      - /home/virajs-server/docker/filebrowser/data/filebrowser_database:/database
      - /home/virajs-server/docker/filebrowser/data/filebrowser_config:/config
    networks:
      - nginx

networks:
  nginx:
    external: true 