services:
  beszel:
    image: henrygd/beszel:latest
    container_name: beszel
    restart: unless-stopped
    ports:
      - "${BESZEL_PORT}:8090"
    volumes:
      - ./data/beszel_data:/beszel_data
      - ./data/beszel_socket:/beszel_socket
    networks:
      - caddy

  beszel-agent:
    image: henrygd/beszel-agent:latest
    container_name: beszel-agent
    restart: unless-stopped
    network_mode: host
    volumes:
      - ./data/beszel_agent_data:/var/lib/beszel-agent
      - ./data/beszel_socket:/beszel_socket
      - /var/run/docker.sock:/var/run/docker.sock:ro
    environment:
      LISTEN: /beszel_socket/beszel.sock
      HUB_URL: "${BESZEL_HUB_URL}" 
      # TOKEN: <token> # universal token (/settings/tokens) to connect the agent

      KEY: "${BESZEL_AGENT_KEY}"    
       
networks:
  caddy:
    external: true      