services:
  yaak:
    image: lscr.io/linuxserver/yaak:latest
    container_name: yaak
    environment:
      - PUID=${PUID}
      - PGID=${PGID}
      - TZ=${TZ}
    volumes:
      - ./data/config:/config
    ports:
      - ${YAAK_PORT_1}:3000
      - ${YAAK_PORT_2}:3001
    shm_size: "1gb"
    restart: unless-stopped
    networks:
      - caddy
networks:
  caddy:
    external: true    