name: tiny10
services:
  windows:
    image: dockurr/windows
    container_name: tiny10
    environment:
      VERSION: "10"
      DISK_SIZE: "100G"
      RAM_SIZE: "8G"
      CPU_CORES: "2"
      USERNAME: "virajs"
      PASSWORD: "test@123"      
    devices:
      - /dev/kvm
      - /dev/net/tun
    cap_add:
      - NET_ADMIN
    ports:
      - 8006:8006
      - 3389:3389/tcp
      - 3389:3389/udp
    volumes:
      - /home/virajs-server/docker/tiny10/data/windows:/storage
      - /home/virajs-server/docker/nextcloud/data/virajs/files/Storage/tiny10-shared:/shared
      - /home/virajs-server/docker/nextcloud/data/virajs/files/Storage/iso/tiny10_23h2_x64.iso:/boot.iso
    restart: unless-stopped
    stop_grace_period: 2m
    networks:
      - nginx
networks:
  nginx:
    external: true      