name: ollama-3b
services:
  ollama-3b:
    image: ollama/ollama
    container_name: ollama-3b
    restart: "no"
    volumes:
      - /home/virajs-server/docker/ollama/data/ollama1b:/root/.ollama
    environment:
      - OLLAMA_KEEP_ALIVE=${OLLAMA_KEEP_ALIVE}
      - OLLAMA_HOST=${OLLAMA_HOST}
    ports:
      - "${OLLAMA_PORT_3B}:11434"
    networks:
      - nginx

networks:
  nginx:
    external: true
