networks:
  nginx:
    external: true

services:

  api:
    networks:
      nginx:
        aliases:
          - librechat  
    volumes:
    - type: bind
      source: ./librechat.yaml
      target: /app/librechat.yaml

  mongodb:
    networks:
      - nginx
  meilisearch:
    networks:
      - nginx
  vectordb:
    networks:
      - nginx
  rag_api:
    networks:
      - nginx