name: moodle
services:
  mariadb:
    image: mariadb
    volumes:
      - /home/virajs-server/docker/moodle/srv/Configs/Databases/Moodle:/var/lib/mysql
    environment:
      - MYSQL_ROOT_PASSWORD=moodle
      - MYSQL_ROOT_USER=root
      - MYSQL_DATABASE=moodle
    networks:
      - nginx

  moodle:
    image: docker.io/bitnami/moodle:latest
    ports:
      - 8080:8080
      - 8443:8443
    environment:
      - MOODLE_DATABASE_HOST=mariadb
      - MOODLE_DATABASE_USER=root
      - MOODLE_DATABASE_PASSWORD=moodle
      - MOODLE_DATABASE_NAME=moodle
      - PUID=1000
      - PGID=1000
    volumes:
      - /home/virajs-server/docker/moodle/srv/Configs/Moodle:/bitnami/moodle
      - /home/virajs-server/docker/moodle/srv/Configs/MoodleData:/bitnami/moodledata
    depends_on:
      - mariadb
    links:
      - mariadb:mariadb
    networks:
      - nginx

networks:
  nginx:
    external: true
