services:
  speedtest-tracker:
    image: lscr.io/linuxserver/speedtest-tracker:latest
    container_name: speedtest-tracker
    restart: unless-stopped
    volumes:
      - ./data/speedtest-tracker/data:/config
    ports:
      - ${SPEEDTEST_PORT}:80
    environment:
      - PUID=${PUID}
      - PGID=${PGID}
      - TZ=${TZ}
      - APP_KEY=${APP_KEY} # Generate app key using https://speedtest-tracker.dev
      - APP_URL=${APP_URL}
      - DB_CONNECTION=${DB_CONNECTION} #optional
      - SPEEDTEST_SCHEDULE=${SPEEDTEST_SCHEDULE} #optional
      - SPEEDTEST_SERVERS=${SPEEDTEST_SERVERS}
      - DB_HOST= #optional
      - DB_PORT= #optional
      - DB_DATABASE= #optional
      - DB_USERNAME= #optional
      - DB_PASSWORD= #optional
      - DISPLAY_TIMEZONE=${DISPLAY_TIMEZONE} #optional
      - PRUNE_RESULTS_OLDER_THAN=0 #optional
    networks:
      - caddy
networks:
  caddy:
    external: true      