services:
  joplin:
    image: lscr.io/linuxserver/joplin:latest
    container_name: joplin
    environment:
      - PUID=${PUID}
      - PGID=${PGID}
      - TZ=${TZ}
    volumes:
      - ./data/config:/config
    ports:
      - ${JOPLIN_PORT_1}:3000
      - ${JOPLIN_PORT_2}:3001
    shm_size: "1gb"
    restart: unless-stopped
    networks:
      - caddy
networks:
  caddy:
    external: true    