services:
  coder:
    image: ghcr.io/coder/coder:latest
    ports:
      - "${CODER_PORT}:7080"
    environment:
      CODER_PG_CONNECTION_URL: "postgresql://${POSTGRES_USER}:${POSTGRES_PASSWORD}@database/${POSTGRES_DB}?sslmode=disable"
      CODER_HTTP_ADDRESS: "0.0.0.0:${CODER_PORT}"
      CODER_ACCESS_URL: "${CODER_ACCESS_URL}"
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
      - ./data/coder_home:/home/coder
    depends_on:
      database:
        condition: service_healthy
    networks:
      - caddy        
  database:

    image: "postgres:17"
    environment:
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
      POSTGRES_DB: ${POSTGRES_DB}
    volumes:
      - ./data/coder_data:/var/lib/postgresql/data
    healthcheck:
      test:
        [
          "CMD-SHELL",
          "pg_isready -U ${POSTGRES_USER:-username} -d ${POSTGRES_DB:-coder}",
        ]
      interval: 5s
      timeout: 5s
      retries: 5
    networks:
      - caddy
networks:
  caddy:
    external: true    