services:
  stirling-pdf:
    image: docker.stirlingpdf.com/stirlingtools/stirling-pdf:latest
    ports:
      - '${STIRLING_PORT}:8080'
    volumes:
      - ./data/trainingData:/usr/share/tessdata # Required for extra OCR languages
      - ./data/extraConfigs:/configs
      - ./data/customFiles:/customFiles/
      - ./data/logs:/logs/
      - ./data/pipeline:/pipeline/
    environment:
      - DISABLE_ADDITIONAL_FEATURES=${DISABLE_ADDITIONAL_FEATURES}
      - LANGS=${LANGS}
    networks:
      - caddy
networks:
  caddy:
    external: true      